from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
from datetime import datetime
from uuid import UUID, uuid4
from typing import List

# --- Models ---
class NoteIn(BaseModel):
    """Model for creating a note, ID and timestamp are generated by the server."""
    content: str
    channel: str
    color: int
    karma: int = 0

class NoteOut(BaseModel):
    """Model for returning a note, includes server-generated fields."""
    id: UUID
    content: str
    channel: str
    timestamp: datetime
    color: int
    karma: int

class VoteData(BaseModel):
    """Model for the vote endpoint."""
    change: int

# --- In-Memory Database ---
# (A simple list to act as our database for now)
db: List[NoteOut] = []

# --- FastAPI App ---
app = FastAPI(
    title="Jodel 2.0 Backend",
    description="API for the Jodel 2.0 Flutter App",
    version="1.0.0",
)

# --- API Endpoints ---
@app.get("/")
def read_root():
    return {"message": "Welcome to the Jodel 2.0 API"}

@app.get("/notes", response_model=List[NoteOut])
def get_notes():
    """Returns all notes, newest first."""
    return sorted(db, key=lambda x: x.timestamp, reverse=True)

@app.post("/notes", response_model=NoteOut, status_code=201)
def add_note(note: NoteIn):
    """Creates a new note."""
    new_note = NoteOut(
        id=uuid4(),
        content=note.content,
        channel=note.channel,
        timestamp=datetime.now(),
        color=note.color,
        karma=note.karma,
    )
    db.append(new_note)
    return new_note

@app.delete("/notes/{note_id}", status_code=204)
def remove_note(note_id: UUID):
    """Deletes a note by its ID."""
    note_to_delete = next((note for note in db if note.id == note_id), None)
    if not note_to_delete:
        raise HTTPException(status_code=404, detail="Note not found")
    db.remove(note_to_delete)
    return

@app.put("/notes/{note_id}", response_model=NoteOut)
def update_note(note_id: UUID, updated_note_data: NoteIn):
    """Updates a note's content, channel, or color."""
    note_index = -1
    for i, n in enumerate(db):
        if n.id == note_id:
            note_index = i
            break
            
    if note_index == -1:
        raise HTTPException(status_code=404, detail="Note not found")
        
    note = db[note_index]
    note.content = updated_note_data.content
    note.channel = updated_note_data.channel
    note.color = updated_note_data.color
    # Karma and timestamp are not updated via this endpoint
    
    db[note_index] = note
    return note

@app.post("/notes/{note_id}/vote", response_model=NoteOut)
def vote_note(note_id: UUID, vote_data: VoteData):
    """Increments or decrements a note's karma."""
    note_index = -1
    for i, n in enumerate(db):
        if n.id == note_id:
            note_index = i
            break

    if note_index == -1:
        raise HTTPException(status_code=404, detail="Note not found")
        
    db[note_index].karma += vote_data.change
    return db[note_index]

# To run the server:
# 1. Make sure you are in the 'notes_app2/backend' directory.
# 2. Install dependencies: pip install -r requirements.txt
# 3. Run uvicorn: uvicorn main:app --reload
# The API will be available at http://127.0.0.1:8000
